defaults: large.yaml
run:
  name: "laion-compound-${date:%Y-%m-%d_%H-%M-%S}"
data:
  val_fraction: 0.005
  num_fixed_preview_samples: 1
  num_random_preview_samples: 1
  loader:
    batch_size: 12
    num_workers: 16
